name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM CI
      working-directory: backend
      run: |
        npm ci
    - name: NPM build
      working-directory: backend
      run: |
        npm run build --if-present
    - name: NPM testing
      working-directory: backend
      run: | 
        npm test
